server:
  port: 9090

spring:
  application:
    name: msvc-task
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microrobot-microservicio
    username: postgres
    password: Alejandro1996nal
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

