server:
  port: 8090

spring:
  application:
    name: msvc-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microrobot-microservicio
    username: postgres
    password: Alejandro1996nal
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  feign:
    client:
      config:
        default:
          requestInterceptors:
            - com.microrobot.user.config.FeignClientInterceptor